### ISSUE TITLE
typo in solution? 

### ISSUE THREAD

**Issue by Wyatt23** [ga-dc/reminders_mongo#2]
line 8 - for us students  - should var 'susy' either have name 'susy' or be var charlie? :) 

var bob = new AuthorModel({name: "bob"});
var susy = new AuthorModel({name: "charlie"});
var tom = new AuthorModel({name: "tom"});

**Comment by RobertAKARobin** [comment]
THAT'S EXACTLY THE WAY WE MEANT IT TO BE.

Just kidding. I'll change it.
